### PR TITLE
feat: add set_social_db_profile_description

### PR DESCRIPTION
**Pull request by PolyProgrammist**
tested here: https://near.social/mob.near/widget/ProfilePage?accountId=truedove38.near

### CODE REVIEW

**Review by petersalomonsen — CHANGES_REQUESTED** [review]
Should we also store the description in the contract storage? So that it can also be used by the web4 handler here:

https://github.com/NEAR-DevHub/neardevhub-contract/blob/main/src/web4/handler.rs#L23

Then we would also be able to show descriptions for other instances such as events/infrastructure-committee.

**Comment by frol** [comment]
@petersalomonsen I think we don't need that after all. Web4 supports view-calls that it resolves on the gateway level, see "Loading data" section https://web4.near.page/

**Review by frol — APPROVED** [review]
The implementation looks good to me

**Comment by petersalomonsen** [comment]
> https://web4.near.page/

True, let's try the web4 preloads instead 👍

**Review by petersalomonsen — APPROVED** [review]

**Pull request merged**
