### PR TITLE
wip: added Rules::Any and modified MembersList::check_permissions

### PR DESCRIPTION
**Pull request by Tguntenaar**
I created a DRAFT because this is probably not ready to merge.

I've changed the permissions as said in issue [#88](https://github.com/near/neardevhub-widgets/issues/88) in neardevhub-widgets repo, however I have got some questions.

Are there any docs related to developing this repository? Might be usefull to add some in the README.md

I noticed there aren't any unit test, which good practices did you guys use to test so far? Just manually deploying it to testnet.

### CODE REVIEW

**Comment by Tguntenaar** [comment]
@ailisp could you review this?

**Comment by ailisp** [comment]
@Tguntenaar Looks like your implementation works! Let's add a test to prove it.

> I noticed there aren't any unit test, which good practices did you guys use to test so far? Just manually deploying it to testnet.

There are some: 

https://github.com/near/neardevhub-contract/blob/575a052b2185b559754dda253322c21911a5afd9/src/access_control/members.rs#L257

https://github.com/near/neardevhub-contract/blob/575a052b2185b559754dda253322c21911a5afd9/src/access_control/rules.rs#L129

You can run them through `cargo test`. I'd suggest to add test a member with any permission can edit: 1. a post with some random labels; 2. a post without any label. And ensure member without "any permission" cannot edit such labels (existing test if passed should guaranteed that).

**Comment by Tguntenaar** [comment]
@ailisp I have added a test. Would you like me to add more?

**Comment by ailisp** [comment]
Thanks! This looks good and the test indeed passes.

**Comment by frol** [comment]
@ailisp I have updated the `team:moderators` permission to use `any` as you mentioned to me. Here is the [near.cli.rs](https://near.cli.rs) command I used (just for future reference):

```
near contract call-function as-transaction devgovgigs.near edit_member json-args '{"member": "team:moderators", "metadata": {"children": ["nearmax.near", "yarotska.near", "bearmans.near", "theori.near", "frol.near"], "description": "Moderators can edit any post", "member_metadata_version": "V0",  "parents": [], "permissions": {"any": ["use-labels", "edit-post"]}}}' prepaid-gas '100.000 TeraGas' attached-deposit '0 NEAR' sign-as devgovgigs.near network-config mainnet
```

**Pull request merged**
